/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app05;

import java.util.Random;

/**
 *
 * @author DiógenesGalileu
 */
public class TelaTeste extends javax.swing.JFrame {

    /**
     * Creates new form TelaTeste
     */
    private VetDados vetDados;
    public TelaTeste() {
        initComponents();
        vetDados=new VetDados();
        //Criar modelo
        TabelaModelo dados = new TabelaModelo(vetDados);
        //Vincular a tabela com o modelo
        jtTabela.setModel(dados);   
        jRdBtn_30ele.setSelected(true);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup_TamanhoVetor = new javax.swing.ButtonGroup();
        btnGroup_Cenario = new javax.swing.ButtonGroup();
        jRdBtn_30ele = new javax.swing.JRadioButton();
        jRdBtn_20kele = new javax.swing.JRadioButton();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_TmnVetor = new javax.swing.JLabel();
        jLabel_Cenario = new javax.swing.JLabel();
        jRdBtn_Aleatorio = new javax.swing.JRadioButton();
        jRdBtn_InvOrd = new javax.swing.JRadioButton();
        jRdBtn_10percent = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabela = new javax.swing.JTable();
        jButton_Exec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGroup_TamanhoVetor.add(jRdBtn_30ele);
        jRdBtn_30ele.setText("30 elementos");

        btnGroup_TamanhoVetor.add(jRdBtn_20kele);
        jRdBtn_20kele.setText("20000 elementos");
        jRdBtn_20kele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdBtn_20keleActionPerformed(evt);
            }
        });

        jLabel_Titulo.setText("Métodos de Ordenação");

        jLabel_TmnVetor.setText("Tamanho do Vetor");

        jLabel_Cenario.setText("Cenário");

        btnGroup_Cenario.add(jRdBtn_Aleatorio);
        jRdBtn_Aleatorio.setText("Aleatório");

        btnGroup_Cenario.add(jRdBtn_InvOrd);
        jRdBtn_InvOrd.setText("Inversamente Ordenado");

        btnGroup_Cenario.add(jRdBtn_10percent);
        jRdBtn_10percent.setText("Grupos 10% iguais");

        jtTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtTabela);

        jButton_Exec.setText("Executar");
        jButton_Exec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRdBtn_10percent)
                    .addComponent(jRdBtn_InvOrd)
                    .addComponent(jRdBtn_Aleatorio)
                    .addComponent(jRdBtn_20kele)
                    .addComponent(jRdBtn_30ele)
                    .addComponent(jLabel_TmnVetor)
                    .addComponent(jLabel_Cenario))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Exec)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Titulo)
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Exec))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_TmnVetor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRdBtn_30ele)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRdBtn_20kele)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Cenario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRdBtn_Aleatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRdBtn_InvOrd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRdBtn_10percent)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ExecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExecActionPerformed
        
        Random novonum = new Random();  
        int[] vetor=null;
        if(jRdBtn_30ele.isSelected()){   
            vetor = new int[30];
            
        }else if(jRdBtn_20kele.isSelected()) {   
            vetor = new int[20000];
           
        }
        //inicio de todos os metodos de ordenamento.
        BubbleSort bubbleSort = new BubbleSort();
        InsertionSort insertionSort = new InsertionSort();
        MergeSort mergeSort = new MergeSort();
        QuickSort quickSort =  new QuickSort();
        
        if(jRdBtn_Aleatorio.isSelected()){
            for (int i = 0; i < vetor.length; i++) {
                vetor[i] = novonum.nextInt(45000)+novonum.nextInt(5000);
            }    
            
        }
        if(jRdBtn_InvOrd.isSelected()){
            int Nmaior = vetor.length;
            for (int i = 0; i < vetor.length; i++) {
                vetor[i] = Nmaior--;
            } 
        }
        if(jRdBtn_10percent.isSelected()){
            
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton_ExecActionPerformed

    private void jRdBtn_20keleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdBtn_20keleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRdBtn_20keleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup_Cenario;
    private javax.swing.ButtonGroup btnGroup_TamanhoVetor;
    private javax.swing.JButton jButton_Exec;
    private javax.swing.JLabel jLabel_Cenario;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_TmnVetor;
    private javax.swing.JRadioButton jRdBtn_10percent;
    private javax.swing.JRadioButton jRdBtn_20kele;
    private javax.swing.JRadioButton jRdBtn_30ele;
    private javax.swing.JRadioButton jRdBtn_Aleatorio;
    private javax.swing.JRadioButton jRdBtn_InvOrd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtTabela;
    // End of variables declaration//GEN-END:variables
}
